#!/bin/bash

# setup.sh
# This script interactively sets up the config.js file for the NotebookLM Chat extension.

echo "-------------------------------------------"
echo " NotebookLM Chat Extension Firebase Setup "
echo "-------------------------------------------"
echo "This script will guide you through creating the 'config.js' file."
echo "Please have your Firebase project's web app configuration details ready."
echo "You can find these in the Firebase console: Project Settings > General > Your apps > Web app."
echo ""

# Prompt user for each configuration value
read -p "Enter your Firebase apiKey: " apiKey
read -p "Enter your Firebase authDomain (e.g., your-project-id.firebaseapp.com): " authDomain
read -p "Enter your Firebase projectId: " projectId
read -p "Enter your Firebase storageBucket (e.g., your-project-id.appspot.com): " storageBucket
read -p "Enter your Firebase messagingSenderId: " messagingSenderId
read -p "Enter your Firebase appId: " appId
read -p "Enter your Firebase measurementId (optional, can be left blank): " measurementId

# Define the output file
CONFIG_FILE="config.js"

# Use a "here document" to write the config.js file
# This is a robust way to write multi-line files in bash.
cat > "$CONFIG_FILE" << EOF
// ----------------------------------------------------------------
// Firebase Configuration
// ----------------------------------------------------------------
// This file was generated by the setup.sh script.
// Do not edit this file directly.
// To re-generate, run the setup.sh script again.
// ----------------------------------------------------------------

export const firebaseConfig = {
  apiKey: "${apiKey}",
  authDomain: "${authDomain}",
  projectId: "${projectId}",
  storageBucket: "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId: "${appId}",
  measurementId: "${measurementId}"
};
EOF

echo ""
echo "-------------------------------------------"
echo "✅ Success! The '${CONFIG_FILE}' has been created."
echo "You are now ready to load the extension in Chrome."
echo "-------------------------------------------"

# Make the script executable
chmod +x setup.sh
